# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IVDevs - Comunidad de Programadores
email: contacto@ivdevs.com
description: > # this means to ignore newlines until "baseurl:"
  Comunidad de programadores IV Región, tenemos como objetivo mejorar el nivel
  técnico de los profesionales del área TI, mediante meetups y eventos de desarrolladores
  para desarrolladores en La Serena, Coquimbo y sus alrededores.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: iv_devs
github_username:  iv-devs
design_username: rocket4ce

analytics: UA-XXXXX-X

gems:
 - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
markdown: kramdown
theme: minima
